import dataShuffler from "../lib/dataShuffler";

const exercises = [
  "calf raises",
  "burpees",
  "reverse burpees",
  "plank star jumps",
  "toe points",
  "plank taps",
  "plank",
  "squat lift",
  "squat jump",
  "crunches",
  "regular push up",
  "bicycle crunches",
  "shrimp squat",
  "shortboard pop ups",
  "longboard pop ups",
  "switch pop ups",
  "active scandasana",
  "mountain climbers",
  "lunges",
  "tricep push up",
  "tricep dips",
  "courtsies",
  "bent leg toe taps",
  "wall sit",
  "prayer squat to fold",
  "surfer squats",
  "kick through burpees",
  "hand stand",
  "kettle bell swings",
  "running high legs",
  "star jumps",
  "kettle bell dips",
  "bear walk",
  "dish hold",
  "cobra paddling holds",
  "on back toe taps",
  "squat pulses",
];

export default dataShuffler(exercises);
