import dataShuffler from "../lib/dataShuffler";

const exercises = [
  "calf raises",
  "burpees",
  "reverse burpees",
  "plank star jumps",
  "toe points",
  "plank taps",
  "plank",
  "squat lift or jump",
  "crunches",
  "regular push up",
  "bicycle crunches",
  "shrimp squat",
  "shortboard pop ups",
  "longboard pop ups",
  "switch pop ups",
  "active scandasana",
  "mountain climbers",
  "lunges",
  "tricep dips / push up",
  "courtsies",
  "bent leg toe taps or slides",
  "wall sit",
  "prayer squat to fold",
  "surfer squats",
  "kick through burpees",
  "hand stand",
  "kettle bell swings",
  "running high legs",
  "star jumps",
  "kettle bell dips",
  "bear walk",
  "dish hold",
  "cobra paddling holds",
];

export default dataShuffler(exercises);
